name: Site CI

on:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install site deps
        working-directory: site
        run: npm ci

      - name: Sync site content
        run: python3 scripts/sync_site_content.py

      - name: Build site
        env:
          BASE_PATH: "/${{ github.event.repository.name }}/"
        working-directory: site
        run: npm run build

